// <auto-generated />
using System;
using LojmanYonetimi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojmanYonetimi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723181022_mgr16")]
    partial class mgr16
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojmanYonetimi.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EngelliMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("GorevId")
                        .HasColumnType("int");

                    b.Property<string>("KurumSicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MedeniDurum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("UnvanId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GorevId");

                    b.HasIndex("KurumSicilNo")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UnvanId");

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Bina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AsansorVarmi")
                        .HasColumnType("bit");

                    b.Property<string>("BinaAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BinaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CatiVarmi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EngelliGirisiVarmi")
                        .HasColumnType("bit");

                    b.Property<int>("KampusId")
                        .HasColumnType("int");

                    b.Property<bool>("OtoparkVarmi")
                        .HasColumnType("bit");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("KampusId");

                    b.ToTable("Binas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Açıklama A",
                            Aktif = true,
                            AsansorVarmi = false,
                            BinaAd = "A Blok",
                            BinaNo = "A1",
                            CatiVarmi = false,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            EngelliGirisiVarmi = false,
                            KampusId = 1,
                            OtoparkVarmi = false,
                            Silinmismi = false
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Açıklama B",
                            Aktif = true,
                            AsansorVarmi = false,
                            BinaAd = "B Blok",
                            BinaNo = "B1",
                            CatiVarmi = false,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            EngelliGirisiVarmi = false,
                            KampusId = 1,
                            OtoparkVarmi = false,
                            Silinmismi = false
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Online açıklama",
                            Aktif = true,
                            AsansorVarmi = false,
                            BinaAd = "Online Ofis",
                            BinaNo = "C1",
                            CatiVarmi = false,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            EngelliGirisiVarmi = false,
                            KampusId = 2,
                            OtoparkVarmi = false,
                            Silinmismi = false
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UstBirimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UstBirimId");

                    b.ToTable("Birims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            BirimAd = "Bilgi İşlem",
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            Silinmismi = false
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GorevAd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorevKisaAd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gorevs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            GorevAd = "Memur",
                            Puan = 0,
                            Silinmismi = false,
                            Sira = 0
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Kampus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KampusAd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Kampus", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Konut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BinaId")
                        .HasColumnType("int");

                    b.Property<string>("DaireAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DaireNo")
                        .HasColumnType("int");

                    b.Property<int>("DaireTuruEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Esyalimi")
                        .HasColumnType("bit");

                    b.Property<int>("IsitmaTuruEnum")
                        .HasColumnType("int");

                    b.Property<int>("KatEnum")
                        .HasColumnType("int");

                    b.Property<int>("KonutDurumEnum")
                        .HasColumnType("int");

                    b.Property<int>("MetreKare")
                        .HasColumnType("int");

                    b.Property<int>("OdaTipiId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("BinaId");

                    b.HasIndex("OdaTipiId");

                    b.ToTable("Konuts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            BinaId = 1,
                            DaireAd = "101 No'lu Daire",
                            DaireNo = 101,
                            DaireTuruEnum = 0,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            Esyalimi = false,
                            IsitmaTuruEnum = 0,
                            KatEnum = 1,
                            KonutDurumEnum = 5,
                            MetreKare = 0,
                            OdaTipiId = 1,
                            Silinmismi = false
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.KullaniciPuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Puan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PuanKuraliId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PuanKuraliId");

                    b.ToTable("KullaniciPuans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            ApplicationUserId = 1,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            Puan = 10m,
                            PuanKuraliId = 1,
                            Silinmismi = false
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.OdaTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OdaAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("OdaTipis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            OdaAd = "1+1",
                            OdaSayisi = 0,
                            Silinmismi = false
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            OdaAd = "2+1",
                            OdaSayisi = 0,
                            Silinmismi = false
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.PersonelAkraba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KonukAdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KonukDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KonukTckn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PersonelAkrabas", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.PuanKurali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AkademikTesvikPuan")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("AylKatSayi")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("KisiBasiKatSayisi")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaksimumPuan")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SabitPuan")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("YilKatSayi")
                        .HasMaxLength(500)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PuanKuralis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Kıdeme göre verilen puan",
                            Ad = "Kıdem Puanı",
                            AkademikTesvikPuan = 0m,
                            Aktif = true,
                            AylKatSayi = 0m,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            KisiBasiKatSayisi = 0m,
                            Kod = "PK001",
                            MaksimumPuan = 100m,
                            SabitPuan = 10m,
                            Silinmismi = false,
                            YilKatSayi = 0m
                        });
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.TercihEdilenKampus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BasvuruId")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KampusId")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("TercihEdilenKampus", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.TercihEdilenKonut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BasvuruId")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KonutId")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("TercihEdilenKonuts", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<bool>("Silinmismi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("UnvanAd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnvanKisaAd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Unvans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DuzenlemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duzenleyen = "system",
                            EklemeTarihi = new DateTime(2025, 7, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ekleyen = "system",
                            Puan = 0,
                            Silinmismi = false,
                            Sira = 0,
                            UnvanAd = "Uzman"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.ApplicationUser", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.Birim", "Birim")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojmanYonetimi.Entities.Gorev", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("GorevId");

                    b.HasOne("LojmanYonetimi.Entities.Unvan", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("UnvanId");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Bina", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.Kampus", "Kampus")
                        .WithMany("Binas")
                        .HasForeignKey("KampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kampus");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Birim", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.Birim", "UstBirim")
                        .WithMany("AltBirimler")
                        .HasForeignKey("UstBirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstBirim");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Konut", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.Bina", "Bina")
                        .WithMany("Konuts")
                        .HasForeignKey("BinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojmanYonetimi.Entities.OdaTipi", "OdaTipi")
                        .WithMany("Konuts")
                        .HasForeignKey("OdaTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bina");

                    b.Navigation("OdaTipi");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.KullaniciPuan", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("KullaniciPuans")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LojmanYonetimi.Entities.PuanKurali", "PuanKurali")
                        .WithMany("KullaniciPuans")
                        .HasForeignKey("PuanKuraliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("PuanKurali");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.PersonelAkraba", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("PersonelAkrabas")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LojmanYonetimi.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.ApplicationUser", b =>
                {
                    b.Navigation("KullaniciPuans");

                    b.Navigation("PersonelAkrabas");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Bina", b =>
                {
                    b.Navigation("Konuts");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Birim", b =>
                {
                    b.Navigation("AltBirimler");

                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Gorev", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Kampus", b =>
                {
                    b.Navigation("Binas");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.OdaTipi", b =>
                {
                    b.Navigation("Konuts");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.PuanKurali", b =>
                {
                    b.Navigation("KullaniciPuans");
                });

            modelBuilder.Entity("LojmanYonetimi.Entities.Unvan", b =>
                {
                    b.Navigation("ApplicationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
